apiVersion: apps/v1
kind: Deployment
metadata:
  name: apachewebsite
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apachewebsite
  template:
    metadata:
      labels:
        app: apachewebsite
    spec:
      containers:
      - name: apachewebsite
        image: tejaskandregula/apachewebsite:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apachewebsite-service
spec:
  type: NodePort
  selector:
    app: apachewebsite
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

